### ISSUE TITLE
InfiniteListView 如何用代码触发下拉刷新

### ISSUE THREAD

**Issue by wakeupyq** [flutterchina/flukit#15]
InfiniteListView 如何用代码触发下拉刷新

**Comment by mengqingmeng** [comment]
在InfiniteListView中使用ScrollController，jumpTo(-100)可以实现下拉刷新。

**Comment by mengqingmeng** [comment]
> InfiniteListView 如何用代码触发下拉刷新
在InfiniteListView中使用ScrollController，jumpTo(-100)可以实现下拉刷新。

**Comment by wendux** [comment]
InfiniteListView 组件已废弃，原因是：

实际场景中基本都需要定制无限列表， InfiniteListView 很难在不经修改的情况下用于实际项目中。
如果提供一个尽可能灵活可配置的 InfiniteListViewPlus，则参数又会过多，并且还是很难避免需要定制。
