### ISSUE TITLE
can you update Dart Packages  to new version?

### ISSUE THREAD

**Issue by linguitang** [flutterchina/flukit#2]
update new version to [Dart Packages  ](https://pub.dartlang.org/)

**Comment by jun3372** [comment]
![image](https://user-images.githubusercontent.com/12887993/49560493-99077180-f94d-11e8-8471-90d88342d3d0.png)
示例源码与仓库文件内容不一致, 请更新一下 [Dart Packages](https://pub.dartlang.org/packages/flukit)
