### ISSUE TITLE
[Swiper]  ScrollPosition.viewportDimension 为空报错

### ISSUE THREAD

**Issue by BigTimo** [flutterchina/flukit#25]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (24234): #0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:175:53)
E/flutter (24234): #1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:382:19)
E/flutter (24234): #2      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:197:16)
E/flutter (24234): #3      _SwiperState.animateToPage (package:flukit/src/swiper.dart:447:11)
E/flutter (24234): #4      _SwiperState._start.<anonymous closure> (package:flukit/src/swiper.dart:408:7)
E/flutter (24234): #5      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (24234): #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24234): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (24234): #8      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (24234): #9      _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter (24234): #10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24234): #11     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (24234): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (24234): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (24234): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by GraceJoJo** [comment]
i met the same error when use "_tabController?.index =index;",  if u see the comment ,can you share your solution for this error, i am looking forward your response.
