### ISSUE TITLE
quick_scrollbar

### ISSUE THREAD

**Issue by Panseng** [flutterchina/flukit#8]

**Comment by Panseng** [comment]
I/flutter (15869): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15869): The following assertion was thrown building QuickScrollbar(dirty, dependencies:
I/flutter (15869): [PrimaryScrollController], state: _QuickScrollBarState#1c371(ticker inactive)):
I/flutter (15869): type '(ScrollNotification) => void' is not a subtype of type '(ScrollNotification) => bool'
I/flutter (15869): 
I/flutter (15869): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15869): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15869): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15869):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (15869): 
I/flutter (15869): When the exception was thrown, this was the stack:
I/flutter (15869): #0      _QuickScrollBarState.build (package:flukit/src/quick_scrollbar.dart:107:23)
I/flutter (15869): #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (15869): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (15869): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #25     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (15869): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (15869): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #113    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #116    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #151    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #156    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #157    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #167    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (15869): #168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #177    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #178    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #179    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #180    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (15869): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (15869): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (15869): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (15869): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (15869): #190    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter (15869): #191    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (15869): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #193    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:508:16)
I/flutter (15869): #194    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #196    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #197    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (15869): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #200    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #201    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (15869): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #203    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (15869): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #206    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #207    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (15869): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #209    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (15869): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #211    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (15869): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (15869): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (15869): #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (15869): #215    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (15869): #216    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (15869): #217    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (15869): #218    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (15869): #219    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (15869): #220    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (15869): #224    _invoke (dart:ui/hooks.dart:209:10)
I/flutter (15869): #225    _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (15869): (elided 3 frames from package dart:async)
I/flutter (15869): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/BpSurfaceComposerClient(15869): Failed to transact (-1)
E/BpSurfaceComposerClient(15869): Failed to transact (-1)

**Comment by Panseng** [comment]
![image](https://user-images.githubusercontent.com/48272139/57294155-56fb7b00-70f9-11e9-9038-f27fe135829e.png)

**Comment by wendux** [comment]
使用最新版重试
